spring.application.name=SpringBootDemo
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=vbooking;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Vbooking@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
